Repository neurobagel/api, pull requests merged in 2024-03, with the labels that each got.

#284 [DOC] Added warning about quoting in `.env` file for Docker commands
  README.md
Labels: pr-documentation

#289 [MNT] Delete leftover copy of add_data_to_graph.sh
  add_data_to_graph.sh
Labels: skip-release

#285 🔄 synced file(s) with neurobagel/workflows
  .github/pull_request_template.md
Labels: _bot

#286 [ENH] Added root endpoint with welcome message and API docs link
  app/main.py
  tests/test_attributes.py
Labels: _community, pr-minor

#290 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/handle_external_pr.yml
Labels: _bot

#291 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/handle_external_pr.yml
  LICENSE
Labels: _bot
