Repository neurobagel/api, pull requests merged in 2024-07, with the labels that each got.

#323 [ENH] Add authentication to `/query` route
  app/api/routers/query.py
  app/api/security.py
  app/main.py
  requirements.txt
  tests/conftest.py
  tests/test_app_events.py
  tests/test_attributes.py
  tests/test_query.py
  tests/test_security.py
Labels: pr-minor-breaking

#325 🔄 synced file(s) with neurobagel/workflows
  .autorc
  .github/workflows/release.yaml
Labels: _bot

#326 [FIX] Exclude sessions missing a queried property from matches
  app/api/utility.py
  tests/test_security.py
  tests/test_utility.py
Labels: pr-bug-fix
