Repository neurobagel/api, pull requests merged in 2024-12, with the labels that each got.

#386 [REF] Manually verify ID token using PyJWT instead of google_auth
  app/api/routers/query.py
  app/api/security.py
  requirements.txt
Labels: release, pr-internal

#387 [ENH] Add consistent badges
  README.md
Labels: pr-internal

#388 [ENH] Implement minimum cell size
  app/api/crud.py
  app/api/utility.py
  tests/test_query.py
Labels: release, pr-minor

#391 [DOC] Update shortcuts in README.md
  README.md
Labels: release, pr-documentation

#394 [MNT] Update labels in dependabot.yml
  .github/dependabot.yml
Labels: skip-release
