Repository neurobagel/api, pull requests merged in 2024-01, with the labels that each got.

#256 [CI] Update pre-commit CI config
  .pre-commit-config.yaml
Labels: skip-release

#255 🔄 synced file(s) with neurobagel/workflows
  .autorc
  .github/pull_request_template.md
  .github/workflows/release.yaml
  .github/workflows/stale.yml
Labels: _bot

#257 🔄 synced file(s) with neurobagel/workflows
  .autorc
Labels: _bot

#259 [FIX] Update pre-commit to work with latest hooks
  requirements.txt
Labels: skip-release

#260 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/build_docker_on_release.yml
Labels: _bot

#264 Support queries of session-level phenotypic attributes
  app/api/crud.py
  app/api/models.py
  app/api/routers/query.py
  app/api/utility.py
  tests/conftest.py
  tests/test_query.py
Labels: pr-minor-breaking

#269 [TST] Refactor tests
  tests/conftest.py
  tests/test_query.py
Labels: pr-tests
