Repository neurobagel/api, pull requests merged in 2024-04, with the labels that each got.

#295 Bumped fastapi, starlette, and typing_extensions
  requirements.txt
Labels: pr-dependencies

#299 🔄 synced file(s) with neurobagel/workflows
  .autorc
Labels: _bot

#305 [FIX] Disable timeout for request to graph
  app/api/crud.py
Labels: pr-bug-fix

#298 [FIX] Delete leftover .template-env and docker-compose.yml
  .template-env
  README.md
  docker-compose.yml
Labels: skip-release
