Repository neurobagel/api, pull requests merged in 2024-10, with the labels that each got.

#342 [MNT] Removed build docker nightly workflow file
  .github/workflows/build_docker.yaml
Labels: pr-internal

#345 [ENH] Implemented `pipeline_version` and `pipeline_name` query fields
  app/api/crud.py
  app/api/models.py
  app/api/routers/query.py
  app/api/utility.py
  docs/default_neurobagel_query.rq
  tests/conftest.py
  tests/test_query.py
Labels: pr-minor-breaking

#347 [MNT] Updated `default_neurobagel_query`
  app/api/utility.py
  docs/default_neurobagel_query.rq
Labels: pr-internal

#349 [FIX] Ensure pipeline variables are returned from the graph in an aggregate query
  app/api/crud.py
  app/api/utility.py
  tests/conftest.py
Labels: pr-bug-fix

#350 [ENH] Add `/pipelines` router & route for fetching available pipeline versions
  app/api/crud.py
  app/api/routers/pipelines.py
  app/api/utility.py
  app/main.py
  tests/test_pipelines.py
  tests/test_utility.py
Labels: pr-minor

#359 [MNT] Update default Neurobagel SPARQL query file and turn into PR checkbox
  .github/pull_request_template.md
  docs/default_neurobagel_query.rq
Labels: pr-documentation

#358 [REF] Split generic `/attributes` endpoints into attribute-specific routers
  app/api/routers/assessments.py
  app/api/routers/attributes.py
  app/api/routers/diagnoses.py
  app/api/routers/pipelines.py
  app/api/routers/route_factory.py
  app/main.py
  tests/conftest.py
  tests/test_app_events.py
  tests/test_attribute_factory_routes.py
  tests/test_attributes.py
Labels: pr-minor-breaking

#362 [MNT] Fix badge link formatting in README.md
  README.md
Labels: skip-release

#364 [FIX] Allow only `"true"` or `None` for `is_control` query parameter
  app/api/models.py
  app/api/utility.py
  tests/test_query.py
Labels: release, pr-bug-fix

#366 [TST] Remove unneeded env file mount from test docker-compose.yml
  .test_env
  docker-compose.yml
Labels: pr-tests

#369 [FIX] Ensure non-agg API doesn't error out when all matches lack pipeline data
  app/api/crud.py
  tests/conftest.py
  tests/test_query.py
Labels: release, pr-bug-fix
