Repository neurobagel/api, pull requests merged in 2024-08, with the labels that each got.

#328 [FIX] Disable redirect slashes globally and remove trailing `/` from `/query`
  Dockerfile
  README.md
  app/api/routers/query.py
  app/main.py
  tests/conftest.py
  tests/test_app_events.py
  tests/test_attributes.py
  tests/test_query.py
  tests/test_routing.py
  tests/test_security.py
Labels: release, pr-minor-breaking

#334 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/build_docker_on_release.yml
Labels: _bot

#333 [FIX] Ensure subjects without imaging sessions are considered in main query
  app/api/utility.py
  docs/default_neurobagel_query.rq
Labels: release, pr-bug-fix

#335 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/build_docker_on_release.yml
Labels: _bot, release

#337 [CI] Fix reference for `DOCKERHUB_REPO` in build_docker_on_release.yml
  .github/workflows/build_docker_on_release.yml
Labels: release, pr-internal
