Repository neurobagel/api, pull requests merged in 2025-02, with the labels that each got.

#408 [MNT] Remove trailing slashes from all paths
  app/api/routers/assessments.py
  app/api/routers/attributes.py
  app/api/routers/diagnoses.py
  app/api/routers/pipelines.py
  app/api/routers/route_factory.py
  app/api/utility.py
  app/main.py
  tests/test_attribute_factory_routes.py
  tests/test_attributes.py
  tests/test_routing.py
Labels: release, pr-patch

#413 [REF] Upgrade to Pydantic>2
  app/api/models.py
  app/api/routers/pipelines.py
  app/api/routers/query.py
  requirements.txt
  tests/test_query.py
Labels: pr-dependencies

#407 Refactor startup/shutdown events to lifespan events
  .pre-commit-config.yaml
  app/api/security.py
  app/main.py
  tests/test_security.py
Labels: _community
